{
 "title": "Node_App",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU_usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"node-app-deployment-.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"node-app-deployment-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"node-app-deployment-.*\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"node-app-deployment-.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}