grafana:
  service:
    type: NodePort
    nodePort: 30009

  adminUser: admin
  adminPassword: "admin"

  sidecar:
    dashboards:
      enabled: true

prometheus:
  service:
    type: NodePort
    nodePort: 30008