grafana:
  service:
    type: NodePort
    nodePort: 30009

  adminUser: admin
  adminPassword: "admin"

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: monitoring

prometheus:
  service:
    type: NodePort
    nodePort: 30008